language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

install:
  - travis_retry composer install --no-interaction

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - mkdir -p build/cov
  - composer test

after_success:
  - bin/php-coveralls -v --exclude-no-stmt

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
    - vendor
    - $HOME/.cache/composer
